name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint code
        run: npm run lint
      - name: Unit tests
        run: npm run test
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: hanhnguyengiahan/battery-ui-image:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
          APP_PATH: ./battery-ui/src
