name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linting
        run: |
          docker run --rm \
            -v $(pwd)/${{ env.APP_PATH }}:/app \
            -w /app \
             mrsangrin/linter-eslint \
            . --ext .js,.jsx,.ts,.tsx
        env:
          APP_PATH: ./battery-ui/src


      - name: Unit testing
        run: npm run test
      - name: Building and pushing Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: hanhnguyengiahan/battery-ui-image:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
          APP_PATH: ./battery-ui/src
